services:
  mongo:
    container_name: mongodb_kurunmi
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
  
  kurunmi:
    container_name: kurunmi
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./:/app
